/*
 Generated by typeshare 1.13.4
*/

/** Outcome of one applied mutation. */
export interface AppliedMutation {
	mutation_id: string;
	entity_id: string;
	/** Human-facing entity key, or the parent ticket key for a comment. */
	key: string;
	seq: number;
}

export enum TokenKind {
	Human = "human",
	Agent = "agent",
}

/** An append-only comment with server-derived author attribution. */
export interface Comment {
	id: string;
	/** Parent ticket ULID. */
	ticket_id: string;
	body: string;
	/** Effective member and accepted token captured when the comment is made. */
	member_id: string;
	token_id: string;
	token_kind: TokenKind;
	agent_name: string | null;
	delegating_member_id: string | null;
	created_at: string;
	seq: number;
}

/** A tenant-wide label referenced by ticket membership. */
export interface Label {
	id: string;
	name: string;
	created_at: string;
	updated_at: string;
	seq: number;
}

export interface LabelTombstone {
	id: string;
	name: string;
	seq: number;
}

export enum Role {
	Admin = "admin",
	Member = "member",
	Viewer = "viewer",
}

export enum MemberStatus {
	Pending = "pending",
	Active = "active",
	Suspended = "suspended",
}

/** The non-sensitive member profile included in normal sync data. */
export interface MemberProfile {
	id: string;
	email: string;
	role: Role;
	status: MemberStatus;
	created_at: string;
	activated_at: string | null;
}

export enum MutationOp {
	Create = "create",
	Update = "update",
	Delete = "delete",
}

export enum Entity {
	Ticket = "ticket",
	Comment = "comment",
	Project = "project",
	Label = "label",
}

/** Ticket workflow state. */
export enum Status {
	Backlog = "backlog",
	Todo = "todo",
	InProgress = "in_progress",
	InReview = "in_review",
	Done = "done",
	Canceled = "canceled",
}

/** Ticket priority, ordered here only for stable parsing and documentation. */
export enum Priority {
	None = "none",
	Low = "low",
	Medium = "medium",
	High = "high",
	Urgent = "urgent",
}

/**
 * Scalar fields a mutation may set. Server validation restricts fields by
 * entity and operation; absent fields are left untouched.
 */
export interface MutationSet {
	/** Required on ticket create and immutable afterward. */
	project?: string;
	title?: string;
	status?: Status;
	priority?: Priority;
	/** Outer `None` omits the field; `Some(None)` explicitly clears it. */
	assignee?: string | null;
	body?: string;
	/** Parent ticket ULID. Required on comment create and immutable afterward. */
	ticket?: string;
	/** Required on project create and immutable afterward. */
	key?: string;
	display_name?: string;
	description?: string;
	name?: string;
}

/**
 * One atomic change to one entity. If any part is rejected, none of the
 * mutation applies.
 */
export interface Mutation {
	/**
	 * Opaque unique idempotency key. CLI-generated values are ULIDs, while
	 * trusted integrations may use a namespaced string. The `mcp:` prefix is
	 * reserved for the server-side MCP adapter and rejected on `/sync`. The
	 * server never orders mutations by this value.
	 */
	mutation_id: string;
	op: MutationOp;
	entity: Entity;
	/** Client-generated entity ULID (also on create). */
	entity_id: string;
	/**
	 * Seq the client last saw for this entity. Required on update; absent on
	 * create. A stale base_seq is not by itself a conflict: the mutation
	 * still applies if it only touches fields the server has not changed
	 * since. A field both sides changed rejects the whole mutation.
	 */
	base_seq?: number;
	set: MutationSet;
	/**
	 * Project owner membership uses add/remove deltas so concurrent changes
	 * to different owners do not replace the whole list.
	 */
	owners_add?: string[];
	owners_remove?: string[];
	/** Ticket-label membership deltas. Values are label ULIDs. */
	labels_add?: string[];
	labels_remove?: string[];
}

/** A rejected mutation. Nothing from it was applied. */
export interface MutationConflict {
	mutation_id: string;
	entity_id: string;
	reason: string;
}

/** A project as stored by the server and cached by the CLI. */
export interface Project {
	id: string;
	/** Immutable human-facing key and mirror directory name. */
	key: string;
	display_name: string;
	description: string;
	/** Active member ULIDs. An empty owner list is valid. */
	owner_ids: string[];
	created_at: string;
	updated_at: string;
	seq: number;
}

export interface ProjectTombstone {
	id: string;
	key: string;
	seq: number;
}

export interface SearchErrorDetail {
	error: string;
	message: string;
	offset: number;
}

export enum SearchMatchSource {
	Key = "key",
	Ticket = "ticket",
	Comment = "comment",
}

export interface SearchMatch {
	source: SearchMatchSource;
	comment_id?: string;
	excerpt: string | null;
}

export enum SearchSort {
	Relevance = "relevance",
	Updated = "updated",
	Created = "created",
}

export interface SearchRequest {
	query: string;
	sort?: SearchSort;
	limit?: number;
	cursor: string | null;
}

export interface SearchResult {
	key: string;
	title: string;
	project: string;
	status: Status;
	priority: Priority;
	assignee: string | null;
	created_at: string;
	updated_at: string;
	match: SearchMatch;
}

export interface SearchResponse {
	results: SearchResult[];
	next_cursor: string | null;
}

/** A ticket as stored by the server and mirrored to markdown. */
export interface Ticket {
	/** Immutable ULID; the protocol speaks ULIDs. */
	id: string;
	/** Human-facing key alias, e.g. `DEMO-1`. Assigned by the server. */
	key: string;
	/** Immutable project ULID. The mirror renders the corresponding key. */
	project: string;
	title: string;
	body: string;
	status: Status;
	priority: Priority;
	/** Assigned member ULID, or null when unassigned. */
	assignee: string | null;
	/** Label ULIDs ordered by their current human-facing names. */
	labels?: string[];
	/** Server-generated UTC timestamps. Clients may not set these fields. */
	created_at: string;
	updated_at: string;
	/** Seq of the last mutation applied to this ticket. */
	seq: number;
}

/** Bootstrap payload from `GET /snapshot`. */
export interface Snapshot {
	projects: Project[];
	labels?: Label[];
	tickets: Ticket[];
	comments: Comment[];
	members?: MemberProfile[];
	/** The seq watermark this snapshot represents. */
	latest_seq: number;
}

export interface SyncRequest {
	protocol_version: number;
	/** Highest seq the client has applied locally; deltas come back from here. */
	last_seq: number;
	mutations: Mutation[];
}

/** A server deletion that removes the corresponding local mirror state. */
export interface TicketTombstone {
	id: string;
	key: string;
	/** Seq assigned to the delete mutation. */
	seq: number;
}

export interface SyncResponse {
	applied: AppliedMutation[];
	conflicts: MutationConflict[];
	/** Full rows for every ticket changed since the request's `last_seq`. */
	deltas: Ticket[];
	/** Comments changed since the request's `last_seq`. */
	comment_deltas: Comment[];
	/** Projects changed since the request's `last_seq`. */
	project_deltas?: Project[];
	/** Labels changed since the request's `last_seq`. */
	label_deltas?: Label[];
	/** Tickets deleted since `last_seq`. */
	tombstones?: TicketTombstone[];
	project_tombstones?: ProjectTombstone[];
	label_tombstones?: LabelTombstone[];
	/**
	 * Current safe profiles. Administrative sequence gaps may occur without
	 * exposing their private records.
	 */
	members?: MemberProfile[];
	latest_seq: number;
}

export enum TokenAccess {
	Read = "read",
	Write = "write",
	Admin = "admin",
}

