/*
 Generated by typeshare 1.13.4
*/

/** Outcome of one applied mutation. */
export interface AppliedMutation {
	mutation_id: string;
	entity_id: string;
	/** Ticket key — tells the client the server-assigned key on create. */
	key: string;
	seq: number;
}

export enum MutationOp {
	Create = "create",
	Update = "update",
}

export enum Entity {
	Ticket = "ticket",
}

/** Ticket workflow state. */
export enum Status {
	Backlog = "backlog",
	Todo = "todo",
	InProgress = "in_progress",
	InReview = "in_review",
	Done = "done",
	Canceled = "canceled",
}

/** Scalar fields a mutation may set. Absent fields are left untouched. */
export interface TicketSet {
	title?: string;
	status?: Status;
	body?: string;
}

/**
 * One atomic change to one entity. All edits to a ticket travel in a single
 * mutation; if any part is rejected, none of it applies.
 */
export interface Mutation {
	/**
	 * Client-generated ULID; the idempotency key. Replaying a mutation_id
	 * returns the original result instead of double-applying.
	 */
	mutation_id: string;
	op: MutationOp;
	entity: Entity;
	/** Client-generated ULID of the ticket (also on create). */
	entity_id: string;
	/**
	 * Seq the client last saw for this entity. Required on update; if the
	 * server has moved past it, the whole mutation is rejected. Absent on create.
	 */
	base_seq?: number;
	set: TicketSet;
}

/** A rejected mutation. Nothing from it was applied. */
export interface MutationConflict {
	mutation_id: string;
	entity_id: string;
	reason: string;
}

/** A ticket as stored by the server and mirrored to markdown. */
export interface Ticket {
	/** Immutable ULID; the protocol speaks ULIDs. */
	id: string;
	/** Human-facing key alias, e.g. `DEMO-1`. Assigned by the server. */
	key: string;
	title: string;
	body: string;
	status: Status;
	/** Seq of the last mutation applied to this ticket. */
	seq: number;
}

/** Bootstrap payload from `GET /snapshot`. */
export interface Snapshot {
	tickets: Ticket[];
	/** The seq watermark this snapshot represents. */
	latest_seq: number;
}

export interface SyncRequest {
	protocol_version: number;
	/** Highest seq the client has applied locally; deltas come back from here. */
	last_seq: number;
	mutations: Mutation[];
}

export interface SyncResponse {
	applied: AppliedMutation[];
	conflicts: MutationConflict[];
	/** Full rows for every ticket changed since the request's `last_seq`. */
	deltas: Ticket[];
	latest_seq: number;
}

